# name: 'terraform-fmt'

# on:
#   push:
#     branches-ignore:
#       - master
#     paths-ignore:
#       - '**.md'

# defaults:
#   run:
#     shell: bash

# jobs:
#   # Job that makes sure that ALL Terraform code is in a canonical format
#   terraform_fmt:
#     name: terraform fmt
#     runs-on: 'ubuntu-latest'
#     steps:
#       # Checkout the repository to the GitHub Actions runner
#       - name: Checkout
#         uses: actions/checkout@v2

#       # Install the latest version of Terraform CLI
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       # Initialize a new or existing Terraform working directory by creating initial files, downloading modules, etc.
#       - name: Terraform Init
#         run: terraform init

#       # Checks that ALL Terraform configuration files adhere to a canonical format
#       - name: Terraform Format
#         run: terraform fmt -check -recursive
