# name: "terraform-validate"

# on:
#   push:
#     branches-ignore:
#       - master
#     paths-ignore:
#       - "**.md"

# defaults:
#   run:
#     shell: bash

# jobs:
#   # Job that makes sure that the syntax in the module is valid
#   terraform_validate:
#     name: terraform validate
#     runs-on: "ubuntu-latest"
#     defaults:
#       run:
#         working-directory: ./
#     steps:
#       # Checkout the repository to the GitHub Actions runner
#       - name: Checkout
#         uses: actions/checkout@v2

#       # Install the latest version of Terraform CLI
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       # Create a provider.tf file to be able to validate module syntax.
#       # This is a issue which is tracked here: https://github.com/hashicorp/terraform/pull/24896
#       - name: Create provider.tf
#         run: |
#           printf 'provider "aws" { \n
#           region = "${{ secrets.AWS_DEFAULT_REGION }}" \n
#           }' > provider.tf
#       # Initialize a new or existing Terraform working directory by creating initial files, downloading modules, etc.
#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Validate
#         run: terraform validate
