# name: "terratest"

# on:
#   pull_request:
#     branches:
#       - master
#     paths-ignore:
#       - "**.md"

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

# jobs:
#   # Job that runs terratest and runs integration test on the infrastructure provisioned.
#   terratest:
#     name: terratest
#     runs-on: "ubuntu-latest"
#     defaults:
#       run:
#         shell: bash
#         working-directory: test

#     steps:
#       # Checkout the repository to the GitHub Actions runner
#       - name: Checkout
#         uses: actions/checkout@v2

#       # Install the latest version of Terraform CLI
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       # Install and set up Golang
#       - name: Set Up Go
#         uses: actions/setup-go@v2

#       # Get all golang dependencies
#       - name: Get dependencies
#         run: go mod tidy

#       # Run terratest
#       - name: Run Terratest
#         run: go test -v -timeout 90m
